source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'MWPhotoBrowser_Example' do
  use_frameworks!

  pod "MWPhotoBrowser", :path => "../"
  pod "SDWebImage", '5.2.5'
  pod "MBProgressHUD", '1.1.0'
  pod "DACircularProgress", '2.3'
end

